spring.application.name=Ndahimana154-portfolio

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio_db
spring.datasource.username=mac
spring.datasource.password=0011

spring.jpa.hibernate.ddl-auto=update

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migrations

